language: elixir
elixir:
  - '1.10'
otp_release:
  - '22.2.6'

services:
  - docker

before_script:
  - docker pull postgres:12
  - docker run -d -p 5432:5432 --env POSTGRES_USER=postgres --env POSTGRES_PASSWORD=postgres postgres:12
  - mix ecto.setup

script:
  - mix test
