version: '3.2'

services:
  monis-app:
    image: monisapp/monis_app:latest
    environment:
      PGUSER: &pg_user postgres
      PGPASSWORD: &pg_pass postgres
      PGDATABASE: monis_app
      PGPORT: 5432
      PGHOST: postgres
      PORT: 4000
      SECRET_KEY_BASE: 5z5r4XqOigXAwXxkNfblMecRnl9z9n2wIf6oj9hGH9ZE4JlHcX6HjOsEWamEXUUu
    restart: on-failure
    ports:
    - 4000:4000
    depends_on:
    - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: *pg_user
      POSTGRES_PASSWORD: *pg_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    restart: always
    volumes:
      - type: bind
        source: ./run/pgdata-prod
        target: /var/lib/postgres/data/pgdata
